/*
 * ProvisioningAPI.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 01/26/2015
 */
using System;

namespace ProvisioningAPI.PCL
{
    public class Configuration
    {
        //The base Uri for API calls
        public const string BaseUri = "http://sandbox.voxbone.com/ws-voxbone";

    }
}